version: "3.2"
services:
    kibana:
        image: kibana:7.0.0
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
        logging:
            driver: "json-file"
            options:
                tag: '{"container_name":"{{.Name}}","service":"{{.ImageName}}"}'

    elasticsearch:
        image: elasticsearch:7.0.0
        ports:
            - 9200:9200
        environment:
            - discovery.type=single-node

    fluent_client:
        build: fluent_client
        volumes:
            - /var/lib/docker/containers/:/var/log/

    fluent_collector:
        build: fluent_collector
